document:
  name: Il Cloud della PA
  description: |
    Le Circolari e i relativi allegati definiscono, in attuazione a quanto previsto
    nel "Piano Triennale per l’informatica nella Pubblica amministrazione 2017-
    2019", approvato con DPCM del 31 maggio 2017, i requisiti di qualificazione dei
    servizi SaaS e dei Cloud Service Provider.   
  tags:
    - "piano triennale"
